### ISSUE TITLE
Visualizing the Color Gradients

### ISSUE THREAD

**Issue by Atharv115** [kyechan99/capsule-render#8]
So First of all, I Would like u to do something to visualize the gradients the way [Github stats themes](https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md) this is done so that it could be better for us users to make a choice as to what gradients do we need our rendered stuff to load in.

I went through the Gradient's file, I did not understand it coz, m an naive to all this stuff.

Btw love ur work, lots of Love and Support from India ![bitmoji](https://sdk.bitmoji.com/render/panel/c70ddd6f-3605-48aa-bdf1-68ad881115b1-d24f89b5-ba29-4739-bfb0-352799c3c9cd-v1.png?transparent=1&palette=1&width=246)

**Comment by Atharv115** [comment]
My Pleasure Brother ![bitmoji](https://sdk.bitmoji.com/render/panel/d6ea9573-7b6b-4374-bcf8-3c38eb0b0972-d24f89b5-ba29-4739-bfb0-352799c3c9cd-v1.png?transparent=1&palette=1&width=246)

**Comment by Atharv115** [comment]
Yeah u may take ur own time to do this

**Comment by kyechan99** [comment]
Hi there.
I've added a little bit of the theme you mentioned.

This is an example added in this patch : [radical](https://capsule-render.vercel.app/api?type=rect&text=RADICAL&fontAlign=30&fontSize=30&desc=Radical%20theme&descAlign=60&descAlignY=50&theme=radical)

![radical](https://capsule-render.vercel.app/api?type=rect&text=RADICAL&fontAlign=30&fontSize=30&desc=Radical%20theme&descAlign=60&descAlignY=50&theme=radical)

But in the gradient mode you mentioned, the problem is how to apply this pattern.
[Github stats theme](https://github.com/anuraghazra/github-readme-stats/blob/master/themes/README.md) contains only solid colors, not gradient images, so I am worried about what to do.
If there is a good way, can you tell me?

**Comment by Atharv115** [comment]
u mean how to make the table like him?
